name: supabase_form
description: "Formation flutter supabase"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.9.1
  flutter_dotenv: ^5.2.1
  flutter_svg: ^2.2.0
  file_picker: ^10.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - .env
  uses-material-design: true
